import { useState, useEffect, useContext } from 'react';
import { Save, ToggleLeft, ToggleRight, Info } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import OrgContext from '../../context/OrgContext';
import { USER_FIELDS, mockOrganizations } from '../../utils/mockData';
import StatusModal from '../../components/common/StatusModal';

export default function RegistrationFields() {
    const { organization: authOrg } = useAuth();
    const orgContext = useContext(OrgContext);
    const organization = orgContext?.currentOrg || authOrg;

    const [enabledFields, setEnabledFields] = useState([]);
    const [hasChanges, setHasChanges] = useState(false);

    // Status modal state
    const [statusModal, setStatusModal] = useState({
        isOpen: false,
        type: 'success',
        title: '',
        message: ''
    });

    useEffect(() => {
        // Load current registration fields for the org
        if (organization) {
            const org = mockOrganizations.find(o => o.id === organization.id);
            if (org?.registration_fields) {
                setEnabledFields(org.registration_fields);
            } else {
                // Default: enable name and email
                setEnabledFields(['name', 'email']);
            }
        }
    }, [organization]);

    const toggleField = (fieldKey) => {
        // 'name' is always required and cannot be disabled
        if (fieldKey === 'name') return;

        setEnabledFields(prev => {
            if (prev.includes(fieldKey)) {
                return prev.filter(f => f !== fieldKey);
            } else {
                return [...prev, fieldKey];
            }
        });
        setHasChanges(true);
    };

    const handleSave = () => {
        try {
            // In a real app, this would save to backend
            // For now, we'll just show success
            setStatusModal({
                isOpen: true,
                type: 'success',
                title: 'Saved!',
                message: 'Registration fields have been updated successfully.'
            });
            setHasChanges(false);
        } catch {
            setStatusModal({
                isOpen: true,
                type: 'error',
                title: 'Error!',
                message: 'Failed to save registration fields.'
            });
        }
    };

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold text-dark-900">Registration Fields</h1>
                    <p className="text-text-light">Configure which fields are collected during user registration</p>
                </div>
                <button
                    onClick={handleSave}
                    disabled={!hasChanges}
                    className={`btn-primary ${!hasChanges ? 'opacity-50 cursor-not-allowed' : ''}`}
                >
                    <Save className="w-5 h-5 mr-2" />
                    Save Changes
                </button>
            </div>

            {/* Info Box */}
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 flex items-start gap-3">
                <Info className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
                <div>
                    <p className="text-sm text-blue-800">
                        <strong>Note:</strong> Some fields are always collected (Name) or automatically generated by the system (OTP, QR Code, Arrival Status, Sessions).
                    </p>
                    <p className="text-sm text-blue-700 mt-1">
                        Toggle fields on/off to customize what information is requested from users during registration.
                    </p>
                </div>
            </div>

            {/* Configurable Fields */}
            <div className="card">
                <h2 className="text-lg font-semibold text-dark-900 mb-4">User Profile Fields</h2>
                <div className="space-y-3">
                    {USER_FIELDS.configurable.map(field => {
                        const isEnabled = enabledFields.includes(field.key);
                        const isRequired = field.key === 'name'; // Name is always required

                        return (
                            <div
                                key={field.key}
                                className={`flex items-center justify-between p-4 rounded-lg border transition-colors ${isEnabled ? 'bg-green-50 border-green-200' : 'bg-gray-50 border-gray-200'
                                    }`}
                            >
                                <div className="flex items-center gap-3">
                                    <div>
                                        <p className="font-medium text-dark-900 flex items-center gap-2">
                                            {field.label}
                                            {isRequired && (
                                                <span className="text-xs bg-red-100 text-red-700 px-2 py-0.5 rounded">Required</span>
                                            )}
                                        </p>
                                        <p className="text-sm text-text-light">
                                            Type: {field.type}
                                            {field.options && ` (${field.options.join(', ')})`}
                                        </p>
                                    </div>
                                </div>
                                <button
                                    onClick={() => toggleField(field.key)}
                                    disabled={isRequired}
                                    className={`p-1 rounded transition-colors ${isRequired ? 'opacity-50 cursor-not-allowed' : 'hover:bg-white/50'
                                        }`}
                                >
                                    {isEnabled ? (
                                        <ToggleRight className="w-10 h-10 text-green-500" />
                                    ) : (
                                        <ToggleLeft className="w-10 h-10 text-gray-400" />
                                    )}
                                </button>
                            </div>
                        );
                    })}
                </div>
            </div>

            {/* System Fields (Read-only) */}
            <div className="card">
                <h2 className="text-lg font-semibold text-dark-900 mb-4">System Fields (Auto-Generated)</h2>
                <p className="text-sm text-text-light mb-4">
                    These fields are automatically managed by the system and cannot be disabled.
                </p>
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">
                    {USER_FIELDS.system.map(field => (
                        <div
                            key={field.key}
                            className="p-3 rounded-lg bg-gray-100 border border-gray-200"
                        >
                            <p className="font-medium text-gray-600">{field.label}</p>
                            <p className="text-xs text-gray-500">Type: {field.type}</p>
                        </div>
                    ))}
                </div>
            </div>

            {/* Status Modal */}
            <StatusModal
                isOpen={statusModal.isOpen}
                onClose={() => setStatusModal({ ...statusModal, isOpen: false })}
                type={statusModal.type}
                title={statusModal.title}
                message={statusModal.message}
            />
        </div>
    );
}
