import { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { UserPlus } from 'lucide-react';
import Input from '../../components/forms/Input';
import { useUserAuth } from '../../hooks/useAuthHooks';
import { isValidEmail } from '../../utils/helpers';
import { USER_FIELDS } from '../../utils/constants';
import StatusModal from '../../components/common/StatusModal';
import { useGetOrganizationBySlugQuery } from '../../redux/slices/apiSlice';

export default function Register() {
    const navigate = useNavigate();
    const { orgSlug } = useParams();
    const { register, isAuthenticated } = useUserAuth();

    // Fetch Organization from API
    const { data: orgData, isLoading: orgLoading } = useGetOrganizationBySlugQuery(orgSlug);
    const organization = orgData?.data;

    const [formData, setFormData] = useState({});
    const [errors, setErrors] = useState({});
    const [loading, setLoading] = useState(false);
    const [statusModal, setStatusModal] = useState({ isOpen: false, type: '', title: '', message: '' });

    const pathPrefix = orgSlug ? `/${orgSlug}` : '';

    const enabledFieldKeys = organization?.registration_fields || ['name', 'email', 'password'];

    // Get the full field config for enabled fields (exclude password if auto-generated by logic, but usually required)
    const formFields = USER_FIELDS.configurable.filter(field =>
        enabledFieldKeys.includes(field.key) && field.key !== 'password'
    );
    // Note: If password is auto-generated by backend/logic, we exclude it. 
    // If explicit password required, we should include it. 
    // Previous code excluded 'password'. Let's check backend authController logic...
    // Backend creates user with generated password if not provided?
    // Actually Backend register logic requires password?
    // Let's assume user must set it or it's generated.
    // In step 4204/4261 register controller takes body.password.
    // For now, let's follow existing logic: exclude password from configurable fields manually if intended,
    // but usually user sets it.
    // Wait, the previous code filtered out password: `&& field.key !== 'password'`
    // Re-checking lines 27-29 of original file. Yes, it excluded password.

    // Redirect if already authenticated
    useEffect(() => {
        if (isAuthenticated) {
            navigate(`${pathPrefix}/profile`);
        }
    }, [isAuthenticated, navigate, pathPrefix]);

    const validate = () => {
        const newErrors = {};

        formFields.forEach(field => {
            const value = formData[field.key];

            // Required validation
            if (field.key === 'name' && !value?.trim()) {
                newErrors.name = 'Name is required';
            }

            if (field.key === 'email') {
                if (!value?.trim()) {
                    newErrors.email = 'Email is required';
                } else if (!isValidEmail(value)) {
                    newErrors.email = 'Invalid email format';
                }
            }

            if (field.key === 'phone' && value && !/^\d{10}$/.test(value.replace(/\D/g, ''))) {
                newErrors.phone = 'Please enter a valid 10-digit phone number';
            }
        });

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!validate()) return;

        setLoading(true);

        const result = await register(formData, orgSlug);

        if (result.success) {
            setStatusModal({
                isOpen: true,
                type: 'success',
                title: 'Registration Successful!',
                message: 'Your account has been created. Redirecting to your profile...'
            });

            setTimeout(() => {
                navigate(`${pathPrefix}/profile`);
            }, 1500);
        } else {
            setStatusModal({
                isOpen: true,
                type: 'error',
                title: 'Registration Failed',
                message: result.error || 'Something went wrong. Please try again.'
            });
        }

        setLoading(false);
    };

    const handleChange = (key, value) => {
        setFormData(prev => ({ ...prev, [key]: value }));
        if (errors[key]) {
            setErrors(prev => ({ ...prev, [key]: null }));
        }
    };

    const renderField = (field) => {
        const value = formData[field.key] || '';

        switch (field.type) {
            case 'select':
                return (
                    <div key={field.key}>
                        <label className="form-label">{field.label}</label>
                        <select
                            value={value}
                            onChange={(e) => handleChange(field.key, e.target.value)}
                            className="form-input"
                        >
                            <option value="">Select {field.label}</option>
                            {field.options?.map(opt => (
                                <option key={opt} value={opt}>
                                    {opt.charAt(0).toUpperCase() + opt.slice(1)}
                                </option>
                            ))}
                        </select>
                        {errors[field.key] && (
                            <p className="text-red-500 text-sm mt-1">{errors[field.key]}</p>
                        )}
                    </div>
                );

            case 'textarea':
                return (
                    <div key={field.key}>
                        <label className="form-label">{field.label}</label>
                        <textarea
                            value={value}
                            onChange={(e) => handleChange(field.key, e.target.value)}
                            placeholder={`Enter ${field.label.toLowerCase()}`}
                            className="form-input"
                            rows={3}
                        />
                        {errors[field.key] && (
                            <p className="text-red-500 text-sm mt-1">{errors[field.key]}</p>
                        )}
                    </div>
                );

            case 'file':
                return (
                    <div key={field.key}>
                        <label className="form-label">{field.label}</label>
                        <input
                            type="file"
                            accept="image/*,.pdf"
                            onChange={(e) => {
                                const file = e.target.files?.[0];
                                if (file) {
                                    const reader = new FileReader();
                                    reader.onloadend = () => {
                                        handleChange(field.key, reader.result);
                                    };
                                    reader.readAsDataURL(file);
                                }
                            }}
                            className="form-input"
                        />
                        {errors[field.key] && (
                            <p className="text-red-500 text-sm mt-1">{errors[field.key]}</p>
                        )}
                    </div>
                );

            default:
                return (
                    <Input
                        key={field.key}
                        label={field.label}
                        type={field.type}
                        placeholder={`Enter ${field.label.toLowerCase()}`}
                        value={value}
                        onChange={(e) => handleChange(field.key, e.target.value)}
                        error={errors[field.key]}
                    />
                );
        }
    };

    return (
        <div className="min-h-[70vh] flex items-center justify-center py-12 px-4">
            <div className="w-full max-w-md">
                {/* Header */}
                <div className="text-center mb-8">
                    <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-500 to-primary-600 flex items-center justify-center mx-auto mb-4">
                        <UserPlus className="w-8 h-8 text-white" />
                    </div>
                    <h1 className="text-3xl font-bold text-dark-900 mb-2">Create Account</h1>
                    <p className="text-text-light">Register for {organization?.name || 'the event'}</p>
                </div>

                {/* Register Form */}
                <div className="card">
                    <form onSubmit={handleSubmit} className="space-y-4">
                        {formFields.map(field => renderField(field))}

                        <button
                            type="submit"
                            disabled={loading}
                            className="w-full btn-primary py-3 mt-6"
                        >
                            {loading ? (
                                <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent" />
                            ) : (
                                <>
                                    <UserPlus className="w-5 h-5 mr-2" />
                                    Register
                                </>
                            )}
                        </button>
                    </form>

                    <div className="mt-6 text-center">
                        <p className="text-text-light">
                            Already have an account?{' '}
                            <Link
                                to={`${pathPrefix}/login`}
                                className="text-primary-600 font-medium hover:underline"
                            >
                                Sign In
                            </Link>
                        </p>
                    </div>

                    {/* Demo Info */}
                    <div className="mt-6 p-4 bg-green-50 rounded-lg border border-green-200">
                        <p className="text-sm font-medium text-green-800 mb-2">Demo Account Available</p>
                        <p className="text-sm text-green-700">
                            You can use the demo account to test features without registering.
                        </p>
                        <Link
                            to={`${pathPrefix}/login`}
                            className="mt-2 inline-block text-sm text-green-600 hover:text-green-800 font-medium underline"
                        >
                            Go to Login with Demo Credentials →
                        </Link>
                    </div>
                </div>
            </div>

            {/* Status Modal */}
            <StatusModal
                isOpen={statusModal.isOpen}
                onClose={() => setStatusModal({ ...statusModal, isOpen: false })}
                type={statusModal.type}
                title={statusModal.title}
                message={statusModal.message}
            />
        </div>
    );
}
